name: midterm

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mern-app
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mern-app
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7.0.11
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app

  redis:
    image: redis:alpine
    networks:
      - mern-app
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    networks:
      - mern-app

volumes:
  mongo_data:
  
networks:
  mern-app:
    driver: bridge